name: Mirror to Public Repo

on:
  push:
    branches: [ development ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        shell: bash
        run: |
          git remote add mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Maximus-Technologies-Uganda/training-hamza-mirror.git
          git push mirror development